### ISSUE TITLE
doesnt work with changing heights

### ISSUE THREAD

**Issue by ethanshar** [oblador/angular-scroll#100]
I am using du-smooth-scroll on a button from one container to another container - this works well.

the only problem is the button also hide some elements in the first container when u click it, which makes the container height to change and therefore cause the scroll to work in a weird way.

when I disabled the height change (prevent from the mentioned element to be hidden) it's working well.
also if i click on the button a second time after the element are already hidden the scroll works good again (seem like it adjusted to the new height). 
but the first time always scrolls bad. 

any suggestion on how to fix this ?

**Comment by ethanshar** [comment]
ok i've notice that it happened after i added angular-animate module to my app.
I guess it delays the rendering for some reason which causes the scrolling to get the wrong height and then to scroll badly.

**Comment by oblador** [comment]
Yeah, that was my initial thought when I read the description. Angular animate will add and remove a few different classes and see what happens on elements using `ng-repeat`, `ng-class`, `ng-hide`, `ng-show` etc. If you'd like to go the extra mile, you can use the promises returned by the [$animate](https://docs.angularjs.org/api/ngAnimate/service/$animate) service and do the scrolling when they resolve or alternatively use a hack like `$timeout` after a few milli seconds. This would require you to take the scrolling code to a controller/directive instead of just a clean template tho. 

Not sure how I can circumvent this behavior in a generalized non-hacky manner.
