### ISSUE TITLE
Cannot bind twice

### ISSUE THREAD

**Issue by aaronjessen** [oblador/angular-scroll#107]
First off, thanks so much for writing these directives; they've played a truly integral part in our application. However, I'm running into a <b>very</b> difficult problem to work out involving the `duScrollspy` directive, and I'd like to know if it's an expected behavior or an issue.

I have a regular dropdown which, upon selecting a particular menu item, will show a dynamically-assigned template (using `ng-include`), containing a group of scrollspy-enabled links (using your `du-scrollspy` and `du-smooth-scroll` attributes). When this group is shown, I am performing a `$compile($('#container').contents())($scope)`, in order to initialize the scrollspies. <b>This works great the first time the group is shown</b>. But, once the group is 'hidden' (the ng-include template is changed), redisplaying the group and calling `$compile` does not create the necessary `context` or scroll handlers (executed in the `spyAPI` factory from your source code). Oddly enough, the smooth scrolling <b>is</b> re-initialized and works when clicking the links.

As far as I can see, the only things being destroyed when the template of scrollspies is hidden is the du-scrollcontainer; that is to say that the `$destroy` is not being triggered for any scroll spies, as is shown in the `duScrollspy` directive (this may or may not be intended or related to this problem; I'm just guessing).

My question to you is whether there is anything I have to do programmatically in order for du-scrollspy-enabled links to be released and rebound, after an initial appearance? Any light you can shed on this would be a big help.

Thanks,

- Aaron Jessen

**Comment by oblador** [comment]
Hi!

Trying to wrap my head around the problem but in a nutshell you have this setup:
* a set of links that are never changed.
* a container on whose child elements the links spy on, however these elements are removed and added from time to time. 

This setup will cause problems since the elements spied on are cached. I guess it would be possible to introduce a setting to not cache it and be happy with the performance hit. 

`du-smoothscroll` only need to fetch the target element on click/tap so there's no use caching there.

**Comment by oblador** [comment]
Closing in lack of response.
